[[headers]]
  for   = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for   = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache"

[[redirects]]
  from   = "/biosignal-sound.html"
  to     = "/"
  status = 301

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
